### ISSUE TITLE
%cython doesn't work in client-server notebooks

### ISSUE THREAD

**Issue by jdemeyer** [sagemath/sagenb#260]
When sagenb is set up not as a single user, but in a client-server model, the directory .sage is not writable. This breaks DATA (which I don't care about) but also %cython (which I do care about) with an error like

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_sage_input_2.py", line 10, in <module>
    exec compile(u'_support_.cython_import_all("/home/sagenb/dotsage/sage_notebook.sagenb/home/J.Demeyer/255/code/sage2.spyx", globals())
  File "", line 1, in <module>

  File "/opt/sage/sage-6.3/local/lib/python2.7/site-packages/sagenb-0.10.8.2-py2.7.egg/sagenb/misc/support.py", line 541, in cython_import_all
    create_local_c_file=create_local_c_file)
  File "/opt/sage/sage-6.3/local/lib/python2.7/site-packages/sagenb-0.10.8.2-py2.7.egg/sagenb/misc/support.py", line 518, in cython_import
    create_local_c_file=create_local_c_file)
  File "/opt/sage/sage-6.3/local/lib/python2.7/site-packages/sage/misc/cython.py", line 412, in cython
    F = open(filename).read()
IOError: [Errno 13] Permission denied: '/home/sagenb/dotsage/sage_notebook.sagenb/home/J.Demeyer/255/code/sage2.spyx'
```

The Sage command cython() works fine, but it's just ugly to write

```
cython("""
print "Hello"
""")
```

instead of

```
%cython
print "Hello"
```

It's also less obvious to find this out.

In other words, what is the reason that %cython isn't just equivalent to cython()?

**Comment by jdemeyer** [comment]
Fixing this should be easy: just make `%cython` equivalent to calling `cython()`.
