### ISSUE TITLE
[BLOCKER] Plots are completely broken due to #340

### ISSUE THREAD

**Issue by jdemeyer** [sagemath/sagenb#348]
Any kind of plotting seems broken in sagenb master due to #340. In the server logs, I see tracebacks like
```
Traceback (most recent call last):
  File "/opt/sage/sage-6.8/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/sage/sage-6.8/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/sage/sage-6.8/local/lib/python2.7/site-packages/sagenb-0.11.4-py2.7.egg/sagenb/flask_version/decorators.py", line 22, in wrapper
    return f(*args, **kwds)
  File "/opt/sage/sage-6.8/local/lib/python2.7/site-packages/sagenb-0.11.4-py2.7.egg/sagenb/flask_version/worksheet.py", line 48, in wrapper
    return f(username, id, **kwds)
  File "/opt/sage/sage-6.8/local/lib/python2.7/site-packages/sagenb-0.11.4-py2.7.egg/sagenb/flask_version/worksheet.py", line 137, in wrapper
    return f(*args, **kwds)
  File "/opt/sage/sage-6.8/local/lib/python2.7/site-packages/sagenb-0.11.4-py2.7.egg/sagenb/flask_version/worksheet.py", line 454, in worksheet_cell_update
    worksheet.check_comp()
  File "/opt/sage/sage-6.8/local/lib/python2.7/site-packages/sagenb-0.11.4-py2.7.egg/sagenb/notebook/worksheet.py", line 3350, in check_comp
    set_restrictive_permissions(target)
  File "/opt/sage/sage-6.8/local/lib/python2.7/site-packages/sagenb-0.11.4-py2.7.egg/sagenb/misc/misc.py", line 414, in set_restrictive_permissions
    os.chmod(filename, x)
OSError: [Errno 1] Operation not permitted: '/home/sagenb/dotsage/sage_notebook.sagenb/home/J.Demeyer/78/cells/66/sage0.png'
```
Most likely, this only applies to multi-user setups.

**Comment by kcrisman** [comment]
Really?  I am at AIMS using 6.8 with all the students and plotting just worked very nicely.  Maybe it's just under certain security settings?  I wonder if @jgutow has seen this.

**Comment by jdemeyer** [comment]
The problem only occurs in master, not in Sage 6.8
