### ISSUE TITLE
sage-on-gentoo: flask-babel upgrade is breaking thing

### ISSUE THREAD

**Issue by kiwifb** [sagemath/sagenb#437]
I have just gone to flask-babel-0.11.2 (from 0.9) and a number of doctests just broke. All in the same way
```
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/sage/doctest/forker.py", line 520, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/lib64/python2.7/site-packages/sage/doctest/forker.py", line 923, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sagenb.notebook.worksheet.Worksheet.html[3]>", line 1, in <module>
        W.html()
      File "/usr/lib64/python2.7/site-packages/sagenb/notebook/worksheet.py", line 2608, in html
        worksheet=self, username=username)
      File "/usr/lib64/python2.7/site-packages/sagenb/notebook/template.py", line 135, in template
        default_context = {'sitename': gettext('Sage Notebook'),
      File "/usr/lib64/python2.7/site-packages/flask_babel/__init__.py", line 552, in gettext
        t = get_translations()
      File "/usr/lib64/python2.7/site-packages/flask_babel/__init__.py", line 227, in get_translations
        [get_locale()],
      File "/usr/lib64/python2.7/site-packages/flask_babel/__init__.py", line 257, in get_locale
        rv = babel.locale_selector_func()
      File "/usr/lib64/python2.7/site-packages/sagenb/flask_version/base.py", line 450, in get_locale
        return g.notebook.conf()['default_language']
      File "/usr/lib64/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
        return getattr(self._get_current_object(), name)
    AttributeError: '_AppCtxGlobals' object has no attribute 'notebook'
```
Any quick fix ideas?

**Comment by dimpase** [comment]
Google returns plenty for "AttributeError: '_AppCtxGlobals' object has no attribute", and none has a lot of sense to me (given that I'm not too much at home with the way notebook operates, with all sorts of delayed executions and callbacks).

**Comment by timokau** [comment]
For reference: https://trac.sagemath.org/ticket/20922

**Comment by fchapoton** [comment]
see https://github.com/sagemath/sagenb/pull/450

**Comment by kiwifb** [comment]
Now that #450 is merged we can close this.
