### ISSUE TITLE
flask 1.0+ has changed the way they initialise extensions

### ISSUE THREAD

**Issue by kiwifb** [sagemath/sagenb#459]
Case in point
```
sage -t --long /usr/lib64/python2.7/site-packages/sagenb/notebook/worksheet.py
**********************************************************************
File "/usr/lib64/python2.7/site-packages/sagenb/notebook/worksheet.py", line 1554, in sagenb.notebook.worksheet.Worksheet.html_ratings_info
Failed example:
    from sagenb.flask_version import base # random output -- depends on warnings issued by other sage packages
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/sage/doctest/forker.py", line 659, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/lib64/python2.7/site-packages/sage/doctest/forker.py", line 1070, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sagenb.notebook.worksheet.Worksheet.html_ratings_info[0]>", line 1, in <module>
        from sagenb.flask_version import base # random output -- depends on warnings issued by other sage packages
      File "/usr/lib64/python2.7/site-packages/sagenb/flask_version/base.py", line 13, in <module>
        from flask.ext.autoindex import AutoIndex
    ImportError: No module named ext.autoindex
```
That because `flask.ext` has been removed and the new procedure to use extension is described at http://flask.pocoo.org/docs/1.0/extensions/#extensions

**Comment by kiwifb** [comment]
OK so there was a PR for that, that I missed. Fixed in 1.1.0.
