### ISSUE TITLE
Conflicting with python3 installed via anaconda

### ISSUE THREAD

**Issue by mzeeqazi** [sagemath/sagenb#463]
## How to fix this.
have installed sagemath from fedora repo
dnf install sage
# attached is the ouput when i call notebook()

sage: notebook()
('The notebook files are stored in:', 'sage_notebook.sagenb')
┌────────────────────────────────────────────────┐
│                                                │
│ Open your web browser to http://localhost:8080 │
│                                                │
└────────────────────────────────────────────────┘
Executing twistd  --pidfile="sage_notebook.sagenb/sagenb.pid" -ny "sage_notebook.sagenb/twistedconf.tac"
Unhandled Error
Traceback (most recent call last):
  File "/home/mzeeqazi/anaconda3/lib/python3.7/site-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/home/mzeeqazi/anaconda3/lib/python3.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/home/mzeeqazi/anaconda3/lib/python3.7/site-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/home/mzeeqazi/anaconda3/lib/python3.7/site-packages/twisted/application/app.py", line 453, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/home/mzeeqazi/anaconda3/lib/python3.7/site-packages/twisted/application/app.py", line 464, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/home/mzeeqazi/anaconda3/lib/python3.7/site-packages/twisted/application/service.py", line 416, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/home/mzeeqazi/anaconda3/lib/python3.7/site-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "sage_notebook.sagenb/twistedconf.tac", line 6, in <module>
    import sagenb.notebook.misc
builtins.ModuleNotFoundError: No module named 'sagenb'

Failed to load application: No module named 'sagenb'

**Comment by mzeeqazi** [comment]
i guess issue mostly with twistd rather than anaconda

have found this somewhere
https://bugzilla.redhat.com/show_bug.cgi?id=1640890

also now when i call notebook(), this is the output
<pre><font color="#0000FF">sage: </font>notebook()
(&apos;The notebook files are stored in:&apos;, &apos;sage_notebook.sagenb&apos;)
┌────────────────────────────────────────────────┐
│                                                │
│ Open your web browser to http://localhost:8080 │
│                                                │
└────────────────────────────────────────────────┘
Executing twistd  --pidfile=&quot;sage_notebook.sagenb/sagenb.pid&quot; -ny &quot;sage_notebook.sagenb/twistedconf.tac&quot;
sh: twistd: command not found
</pre>

**Comment by embray** [comment]
If you want to run the sagenb the best way is probably to run `sage -notebook=sagenb`, in any case.
